version: '3'
services:
  buapi-backend:
    container_name: buapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork


  buapi-gateway:
    container_name: buapi-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    depends_on:
      - buapi-backend

  buapi-interface:
    container_name: buapi-interface
    build:
      context: ./buinterface
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - mynetwork

# 网络，不定义的话就是默认网络
networks:
  mynetwork:
