server:
  port: 8002

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://buapi-interface:8001
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=gateway, 123456
            - AddRequestParameter=color, blue
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    web-application-type: reactive
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace


dubbo:
  application:
    name: dubbo-springboot-demo-provider
  registry:
    address: nacos://nacos:8848

