spring:
  application:
    name: buapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buapi
    username: root
    password: root
#    url: jdbc:mysql://nacosconfig.c7uh9k65ecwd.us-east-1.rds.amazonaws.com:3306/buapi
#    username: root
#    password: mjiIXRNwb7nU5zMPZnuM
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
    timeout: 5000
server:
  port: 8080
  servlet:
    context-path: /api
#  ssl:
#    key-store: classpath:api-backend.p12
#    key-alias: api-backend
#    key-store-password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 这段仅供测试
#buapi:
#  client:
#    access-key: harvey
#    secret-key: 12345678

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  registry:
    address: nacos://localhost:8848

#aws:
#  accessKeyId: your-access-key-id
#  secretKey: your-secret-key
#  region: your-region
gateway:
  host: localhost
  port: 8002